name: Programlabbet Blog
layout_spectrum: 0.8257661797106266
typography_spectrum: 0.4844775968231261
color:
  brandStrength: 0.15913169970735908
  lightness: 0.042595914332196116
  saturation: 0.892442065756768
  rhythmicContrast: 0.7192677680868655
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7386be08-aeea-4fb0-9f10-9f28863f578f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7386be08-aeea-4fb0-9f10-9f28863f578f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Automating Myself
description: The quest for an artificial coworker
github: true
